version: '3'
services:
    mosquitto:
        image: "eclipse-mosquitto:latest"
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - ./config:/mosquitto/conf
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
        command: ["/usr/sbin/mosquitto","-c","/mosquitto/conf/mosquitto.conf"]
        
        ports:
        - "1883:1883"
        
        #tty: true
        #environment:
        #    USER_ID: "1001"
        #    GROUP_ID: "1001"
            
